###  ndarray Manipulation -1

In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5))  #sample-10, feature-5

In [2]:
arr.shape

(10, 5)

In [5]:
# reshape of array

b = arr.reshape(5, 10)

b.shape
b.ndim
b

array([[ 9, 62,  1, 76, 62, 13, 19, 15, 27, 82],
       [14, 24, 47,  4, 31, 47, 74, 24, 25, 32],
       [10, 39, 79, 40, 93, 88,  7, 88, 73, 23],
       [58, 81, 73, 95, 86, 33, 33, 93, 32,  1],
       [12, 76, 88, 83, 46, 94, 56, 72, 28, 41]], dtype=int32)

In [6]:
# dimention convert 

flatten = b.flatten()
#row wise combine
print(flatten)
print(flatten.ndim)

#column wise combine

columnWiseFlattening = np.ravel(b, order= 'F')

print(columnWiseFlattening)

[ 9 62  1 76 62 13 19 15 27 82 14 24 47  4 31 47 74 24 25 32 10 39 79 40
 93 88  7 88 73 23 58 81 73 95 86 33 33 93 32  1 12 76 88 83 46 94 56 72
 28 41]
1
[ 9 14 10 58 12 62 24 39 81 76  1 47 79 73 88 76  4 40 95 83 62 31 93 86
 46 13 47 88 33 94 19 74  7 33 56 15 24 88 93 72 27 25 73 32 28 82 32 23
  1 41]


In [12]:
a = np.random.randint(1, 10, size=(2, 3))  #sample-10, feature-5

b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

[[9 5 2]
 [4 7 1]]
[[27 24 23]
 [20 22 20]]


### concatenate

In [14]:
con_row = np.concatenate((a,b), axis= 0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis= 1) # col wise
print(con_col)

[[ 9  5  2]
 [ 4  7  1]
 [27 24 23]
 [20 22 20]]
[[ 9  5  2 27 24 23]
 [ 4  7  1 20 22 20]]


In [ ]:
# error

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

r = np.concatenate((x,y), axis= 0)
#error
# r1 = np.concatenate((x,y), axis= 1)
print(r)
# print(r1)

[[9 1 7]
 [6 8 4]
 [3 9 2]]
