###  ndarray Manipulation -1

In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5))  #sample-10, feature-5

In [2]:
arr.shape

(10, 5)

In [2]:
# reshape of array

b = arr.reshape(5, 10)

b.shape
b.ndim
b

array([[55, 67, 47, 78, 20, 68, 36,  6, 99, 27],
       [21, 73, 20, 97, 86, 48, 39, 48, 74, 59],
       [79, 39, 62, 11, 93, 68,  9, 12, 53, 45],
       [ 2, 59,  6, 81, 17, 64, 63, 79, 70, 84],
       [73, 65, 19, 79, 88, 76, 82, 26, 45, 23]], dtype=int32)

In [3]:
# dimention convert 

flatten = b.flatten()
#row wise combine
print(flatten)
print(flatten.ndim)

#column wise combine

columnWiseFlattening = np.ravel(b, order= 'F')

print(columnWiseFlattening)

[55 67 47 78 20 68 36  6 99 27 21 73 20 97 86 48 39 48 74 59 79 39 62 11
 93 68  9 12 53 45  2 59  6 81 17 64 63 79 70 84 73 65 19 79 88 76 82 26
 45 23]
1
[55 21 79  2 73 67 73 39 59 65 47 20 62  6 19 78 97 11 81 79 20 86 93 17
 88 68 48 68 64 76 36 39  9 63 82  6 48 12 79 26 99 74 53 70 45 27 59 45
 84 23]


In [4]:
a = np.random.randint(1, 10, size=(2, 3))  #sample-10, feature-5

b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

[[3 5 6]
 [5 1 8]]
[[29 27 22]
 [25 27 28]]


### concatenate

In [5]:
con_row = np.concatenate((a,b), axis= 0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis= 1) # col wise
print(con_col)

[[ 3  5  6]
 [ 5  1  8]
 [29 27 22]
 [25 27 28]]
[[ 3  5  6 29 27 22]
 [ 5  1  8 25 27 28]]


In [6]:
# error

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

r = np.concatenate((x,y), axis= 0)
#error
# r1 = np.concatenate((x,y), axis= 1)
print(r)
# print(r1)

[[4 5 9]
 [2 3 6]
 [9 9 3]]


In [7]:
#transpose matrix
mat  = np.array([
    [10, 20, 30],
    [30, 40, 50]
])

transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [8]:
# array split

a = np.random.randint(1, 10, size=(10, )) 
splitted_array = np.array_split(a, 3)

print(splitted_array)

# split --> equal division
# splitted_array = np.split(a, 3)


[array([7, 9, 6, 9], dtype=int32), array([3, 8, 8], dtype=int32), array([2, 3, 2], dtype=int32)]
