###  ndarray Manipulation -1

In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5))  #sample-10, feature-5

In [2]:
arr.shape

(10, 5)

In [2]:
# reshape of array

b = arr.reshape(5, 10)

b.shape
b.ndim
b

array([[55, 67, 47, 78, 20, 68, 36,  6, 99, 27],
       [21, 73, 20, 97, 86, 48, 39, 48, 74, 59],
       [79, 39, 62, 11, 93, 68,  9, 12, 53, 45],
       [ 2, 59,  6, 81, 17, 64, 63, 79, 70, 84],
       [73, 65, 19, 79, 88, 76, 82, 26, 45, 23]], dtype=int32)

In [3]:
# dimention convert 

flatten = b.flatten()
#row wise combine
print(flatten)
print(flatten.ndim)

#column wise combine

columnWiseFlattening = np.ravel(b, order= 'F')

print(columnWiseFlattening)

[55 67 47 78 20 68 36  6 99 27 21 73 20 97 86 48 39 48 74 59 79 39 62 11
 93 68  9 12 53 45  2 59  6 81 17 64 63 79 70 84 73 65 19 79 88 76 82 26
 45 23]
1
[55 21 79  2 73 67 73 39 59 65 47 20 62  6 19 78 97 11 81 79 20 86 93 17
 88 68 48 68 64 76 36 39  9 63 82  6 48 12 79 26 99 74 53 70 45 27 59 45
 84 23]


In [4]:
a = np.random.randint(1, 10, size=(2, 3))  #sample-10, feature-5

b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

[[3 5 6]
 [5 1 8]]
[[29 27 22]
 [25 27 28]]


### concatenate

In [5]:
con_row = np.concatenate((a,b), axis= 0) # row wise

print(con_row)

con_col = np.concatenate((a,b), axis= 1) # col wise
print(con_col)

[[ 3  5  6]
 [ 5  1  8]
 [29 27 22]
 [25 27 28]]
[[ 3  5  6 29 27 22]
 [ 5  1  8 25 27 28]]


In [6]:
# error

x = np.random.randint(1, 10, size=(2, 3))
y = np.random.randint(1, 10, size=(1, 3))

r = np.concatenate((x,y), axis= 0)
#error
# r1 = np.concatenate((x,y), axis= 1)
print(r)
# print(r1)

[[4 5 9]
 [2 3 6]
 [9 9 3]]


In [7]:
#transpose matrix
mat  = np.array([
    [10, 20, 30],
    [30, 40, 50]
])

transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [8]:
# array split

a = np.random.randint(1, 10, size=(10, )) 
splitted_array = np.array_split(a, 3)

print(splitted_array)

# split --> equal division
# splitted_array = np.split(a, 3)


[array([7, 9, 6, 9], dtype=int32), array([3, 8, 8], dtype=int32), array([2, 3, 2], dtype=int32)]


## arithmetic operator and mathematical function

In [10]:
x = np.array([10, 20, 30, 40])
y = np.array([2, 3, 4, 5])

add = x + y
print(add)

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

remainder = x % y
print(remainder)


[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [14]:
# mathematical function

#trigonometry

#sin, cos, tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

rad_con = np.deg2rad(deg_con)
print(rad_con)



[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]
[10. 20. 30. 40.]


In [21]:
#(google search numpy mathematical functions)

#log
x = np.array([10, 20, 30, 40, 100, 16])
base_10_log_val = np.log10(x)
print(base_10_log_val)

div_by_2 = np.log2(x)
print(div_by_2)

sqrt = np.sqrt(x)
print(sqrt)

sum = np.sum(x)
print(sum)

cumul = np.cumulative_sum(x)
print(cumul)


[1.         1.30103    1.47712125 1.60205999 2.         1.20411998]
[3.32192809 4.32192809 4.9068906  5.32192809 6.64385619 4.        ]
[ 3.16227766  4.47213595  5.47722558  6.32455532 10.          4.        ]
216
[ 10  30  60 100 200 216]


## sorting

In [24]:
# inplace 
x = np.array([10, 8, 16, 100])

z= x.copy()
print(z)

z.sort()

print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [27]:
#copy sorting
print(x)

sort_arr = np.sort(x)

print(sort_arr)

print(x)


[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [33]:
#2d array sorting

mat = np.array([
    [10, 3, 5],
    [8, 4, 9]
])

# horizon axis = 1

hor_sort = np.sort(mat, axis= 1)
print(hor_sort)

# vartical axis = 0

vart_sort = np.sort(mat, axis= 0)
print(vart_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


## searching

In [34]:
print(x)

[ 10   8  16 100]


In [ ]:
# np.where(condition, x, y) if true -> x, otherwise replace with y 

index = np.where(x == 16) #  returns index

print(index)

arr = np.where(x > 8, x, 0) # returns array

print(arr)

(array([2]),)
[ 10   0  16 100]


In [40]:
print(mat)

[[10  3  5]
 [ 8  4  9]]


In [44]:
index = np.where(mat > 8) # returns index
print(index)

arr = np.where(mat > 8, mat, 0)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [49]:
x = np.array([10,100, 8, 16, 100])

max_val_indx = np.argmax(x)
print(max_val_indx)

min_val_indx = np.argmin(x)
print(min_val_indx)

1
2


## counting in ndarray

In [60]:
a = np.random.randint(1, 100, size=(100,))
print(a)

[31 24 37 17 70 69 86 11 52 17 66 41  4 76 18  9 52 25 61 55 79 42  4 19
 96 76 64 95 65 11 74 87 40 52 66 42 49 35  8 67 51  6 53 24  4 51 54 19
 16 19 31 75 20 22 17 12 46 99  7 29 66 69 58 94 95 98 18 90 26 96 85 85
 52 62 76 88 69 73 54 73 77 99 33 13 13 59 50 50  2 87 26 42 44 73 99 81
 92 10  4 40]


In [61]:
val_greater_than_60 = np.count_nonzero(a == 21)
print(val_greater_than_60)

0


In [64]:
unique_val, count = np.unique(a, return_counts= True)
print(unique_val)
print(count)

[ 2  4  6  7  8  9 10 11 12 13 16 17 18 19 20 22 24 25 26 29 31 33 35 37
 40 41 42 44 46 49 50 51 52 53 54 55 58 59 61 62 64 65 66 67 69 70 73 74
 75 76 77 79 81 85 86 87 88 90 92 94 95 96 98 99]
[1 4 1 1 1 1 1 2 1 2 1 3 2 3 1 1 2 1 2 1 2 1 1 1 2 1 3 1 1 1 2 2 4 1 2 1 1
 1 1 1 1 1 3 1 3 1 3 1 1 3 1 1 1 2 1 2 1 1 1 1 2 2 1 3]
